### ISSUE TITLE
Substitute total curve with average curve in the analysis tab

### ISSUE THREAD

**Issue by pozz94** [dekkerglen/CubeCobra#418] opened 2019-09-17 08:27 UTC
As a user, I would like if the total curve in the analysis tab would be substituted by an average curve.

This way the information is preserved but the display of such information would become much clearer.

Now all other colors are squashed down and I have to disable the total curve every time if I want to see them.

**Comment by dekkerglen** [comment] 2019-09-17 11:22
Duplicate of #19

**Closed by dekkerglen** 2019-09-17 11:22 UTC
Labels: duplicate
