### ISSUE TITLE
Option to prevent duplicates in custom draft format

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1622] opened 2020-09-29 18:05 UTC
As a user, I would like a checkbox in the custom draft format editor, that when checked, prevents duplicate cards from appearing in any given pack. This would help with set cubes, to prevent duplicate commons (this is prevented in IRL booster packs using sheet collation anyway)

**Comment by ruler501** [comment] 2020-10-24 20:07
Duplicate of #1501

**Closed** 2020-10-25 02:41 UTC
Labels: enhancement, good first issue
