### ISSUE TITLE
Card replacements are displayed the wrong way around.

### ISSUE THREAD

**Issue by HansonWK** [dekkerglen/CubeCobra#2308] opened 2022-07-12 11:19 UTC
Before 2 weeks ago, when you replaced a card, it would display in the blog as
Old Card -> New Card

Now it displays
New Card -> Old Card.

**To Reproduce**
Update a blog using the replace card feature. Compare to any cube with changed from more than 2 weeks ago.

In the screenshot below, I cut Mind's Desire, Lutri, and New blood.
Chulane, Riellee, and Tuteledge were the additions.
But at some point the order changed.

**Screenshots**
<img width="460" alt="image" src="https://user-images.githubusercontent.com/7226816/178478190-3438e26c-32e5-4965-949b-4ef1aaa79914.png">

**Comment by Eastmanistan** [comment] 2022-07-31 21:32
To be clear old posts are still "oldCard > newCard" while new posts are "newCard > oldCard".  Since they're all going through the same component this makes me think that the problem is the data.

In the below Ferrous went in replacing Gisela 
![Screenshot from 2022-07-31 14-19-03](https://user-images.githubusercontent.com/7650152/182046140-2a978866-96ae-4da8-ba3e-cb75d274fb3c.png)

and here Coalition Victory went in replacing Atraxa

![inout](https://user-images.githubusercontent.com/7650152/182046019-475e1a7d-9ae4-4399-b401-a9db215e3471.png)

**Comment by dekkerglen** [comment] 2022-08-01 20:16
This is fixed on the branch "dynamo"

**Closed** 2023-03-07 20:10 UTC
