### ISSUE TITLE
Advanced Filter Dialog generates wrong syntax for Name filter

### ISSUE THREAD

**Issue by Zenoguy3** [dekkerglen/CubeCobra#407] opened 2019-09-16 00:20 UTC
On advanced filter dialog, Card name field should generate "name: ..." for the name filter, but instead generates "n: ..." and therefore displays an invalid search string error.
The "name: ..." syntax works properly.

**Comment by hallc** [comment] 2019-09-22 00:40
Please assign this to me.

**Comment by hallc** [comment] 2019-09-25 23:45
I can no longer reproduce this issue on `master`.  The advanced filter dialog is generating the correct syntax from both the Edit Cube and Compare screens.  I suspect that this issue was fixed in #470.

However, the problematic bit from `editcube.js` is still present:

```javascript
$('#applyAdvancedFilterButton').click(function(e) {
  e.preventDefault();

  var str = '';

  if ($('#filterName').val().length > 0) {
    str += 'n:' + $('#filterName').val();
  }
```

It looks like that method is no longer called.  Did the react conversion leave us with some dead filtering code that can be removed?

/cc @phulin

**Comment by phulin** [comment] 2019-09-26 01:05
Yep, that code is dead and can be removed. I'll submit a cleanup PR after
the release.

**Closed** 2019-10-01 14:35 UTC
Labels: bug
