### ISSUE TITLE
Download Decks

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#123] opened 2019-08-23 13:42 UTC
As a user, I would like to be able to download decks in specified formats.

Let's try to get a couple formats such that we will be friendly with all the major deck building websites, and also .csv for those who prefer excel

**Comment by emmett9001** [comment] 2019-09-08 05:11
This looks like a duplicate of https://github.com/dekkerglen/CubeCobra/issues/24

**Comment by dekkerglen** [comment] 2019-09-19 17:18
Closed #24 
Additional deck formats requested: Riptidelab forum format

**Closed** 2020-03-12 04:40 UTC
Labels: enhancement
