### ISSUE TITLE
Upload Decklist should use a GUI

### ISSUE THREAD

**Issue by mikeymischief** [dekkerglen/CubeCobra#1735] opened 2020-11-23 07:01 UTC
**What would you like to be able to do?**
Currently uploading decklists, you have to type out each of the cards. This wouldn't necessarily be a bad thing, but if you mess up, there is no "going back" and editing your mistake. You have to type it all out again. Heaven forbid, you type on your ipad, which uses the "wrong" apostrophe. 

**Describe how you would use the feature**
I, ultimately, would like to have a GUI of the cube and you could click each of the cards so that I don't have to spell them out (and when choosing basics, it should prompt for a quantity). It prevents typos, should be able to specify your exact card (things like typing out "green sun's zenith" doesn't work) image, and would generally be more friendly on ipad/mobile.

**Comment by dekkerglen** [comment] 2020-11-23 14:21
Duplicate of #1178

**Closed by dekkerglen** 2020-11-23 14:21 UTC
