### ISSUE TITLE
Copy a historical version of a cube

### ISSUE THREAD

**Issue by tctn27** [dekkerglen/CubeCobra#2251] opened 2022-04-05 06:08 UTC
Considering CubeCobra already stores the chagelogs for each cube, would it be possible to make a function to make a copy of a cube at a given update in the past? Say, by duplicating the cube then applying the changes between the present and then in reverse order.

I think this would be a really useful feature for people with older cubes, and help give context to newer designers when looking through older updates to understand the intent of the changes given their environment.

**Comment by lunakv** [comment] 2022-04-09 18:59
This looks like a duplicate of #1161, unless you feel like you want something that doesn't cover.

**Comment by dekkerglen** [comment] 2022-05-19 19:46
Closing as duplicate

**Closed by dekkerglen** 2022-05-19 19:46 UTC
