### ISSUE TITLE
Allow specifying versions when using bulk import

### ISSUE THREAD

**Issue by dekkerglen** [dekkerglen/CubeCobra#1592] opened 2020-09-11 15:54 UTC
I believe we used to support this, but it is either broken now, or was removed by mistake. We should support the syntax: `Island [mh1]` and `Island [mh1-111]` to specify specific version for bulk upload

**Comment by ruler501** [comment] 2020-10-24 20:03
Duplicate of #1306

**Closed** 2020-10-25 02:40 UTC
Labels: enhancement
