### ISSUE TITLE
A maybeboard to hold potential cube inclusions

### ISSUE THREAD

**Issue by d5c4b3** [dekkerglen/CubeCobra#246] opened 2019-09-04 13:45 UTC
Have a dedicated area to put potential inclusions for the cube so that I don't forget about it. This area would not count towards any of the cube's statistics, but would be displayed on the cube listing page. Controls to easily move cards to and from this area would also be provided.

Currently users can use blog posts and the overview to track maybeboard cards. So this is not a pressing feature.

**Comment by dekkerglen** [comment] 2019-09-04 14:04
Sideboard/maybeboard is a highly request feature.

**Comment by lane-eden** [comment] 2019-09-13 21:51
duplicate of #125

**Closed** 2020-01-11 02:58 UTC
Labels: enhancement
