### ISSUE TITLE
Deck Arrangement is based on Original Drafter's Page Resolution

### ISSUE THREAD

**Issue by haganbmj** [dekkerglen/CubeCobra#511] opened 2019-09-27 03:08 UTC
**Describe the bug**
When constructing a deck the card arrangement is based on the available window size, with cmc columns being combined and multi-row arrangements being used.
This sets the final display of the deck, regardless of what the viewer's resolution is.

Ex: https://cubecobra.com/cube/deck/5d8d79c3884bf5349176e316

**To Reproduce**
1. Draft a deck using a smaller screen resolution.
2. Complete the draft and Save the deck.
3. View the page using a larger screen resolution.

**Expected behavior**
Deck arrangement should be based on structured rules based on device resolution, or in some future state based on one of multiple custom display options.

**Screenshots**

Draft Resolution features groupings of creatures and spells.
Page Width: 851px
<img width="796" alt="cubecobra-decks-1" src="https://user-images.githubusercontent.com/15820761/65738980-c1fe1c00-e0b1-11e9-8ae1-e75d4ef94356.png">

Increased screen resolution shifts some columns to the previous row.
Page Width: 1261px
<img width="826" alt="cubecobra-decks-2" src="https://user-images.githubusercontent.com/15820761/65738983-c3c7df80-e0b1-11e9-96e9-c196da40cc23.png">

**Desktop (please complete the following information):**
Firefox Nightly 71.0a1 (2019-09-25) (64-bit)

**Comment by dekkerglen** [comment] 2019-09-27 03:09
Duplicate of #78, but you are much more descriptive so I'll close the other issue.

**Comment by dekkerglen** [comment] 2019-09-27 03:10
Quoting original issue:

> When a deck is saved with a low screen width, then viewed with a larger screen width, the bottom columns move upwards and everything gets mismatched.
> 
> Create a variable that saves the number of columns in the draft object, and when the draft is loaded into a screen that is too wide, take note of this variable and add empty columns such that column at position == num_cols will be the first element in the second row.

**Comment by haganbmj** [comment] 2019-09-28 23:42
Ah whoops, didn't pick the right search terms I guess.
Thanks for linking the two.

**Closed** 2019-12-29 02:58 UTC
Labels: bug
