### ISSUE TITLE
Allow building deck from full cube

### ISSUE THREAD

**Issue by ruler501** [dekkerglen/CubeCobra#1376] opened 2020-05-24 22:58 UTC
**What would you like to be able to do?**
Allow loading the whole cube into the deck editor to build a deck. 

**Describe how you would use the feature**
Use it to upload deck lists and show best possible versions of an archetype. 

**Additional context**
Should probably load into sideboard and let the user move things into main.

**Comment by dekkerglen** [comment] 2020-05-25 21:18
Duplicate of #1178

**Closed by dekkerglen** 2020-05-25 21:18 UTC
Labels: enhancement
