### ISSUE TITLE
Allow specifying printing of cards in blog posts and overview

### ISSUE THREAD

**Issue by phulin** [dekkerglen/CubeCobra#277] opened 2019-09-06 03:45 UTC
User requests being able to put a specific printing in blog post text and in cube overview.

**Comment by dekkerglen** [comment] 2019-09-06 16:01
The only way I could see this is having the ability to write out the full 'unique' name, in the same format for cube image selection. Thoughts on this, in addition to how it works now?

**Comment by dekkerglen** [comment] 2020-01-14 17:31
duplicate of #287

**Closed by dekkerglen** 2020-01-14 17:31 UTC
Labels: enhancement
