### ISSUE TITLE
Third level of differentiation in multicolored section of list view

### ISSUE THREAD

**Issue by demern** [dekkerglen/CubeCobra#547] opened 2019-09-30 15:44 UTC
Right now, when I set my 'Primary Sort' as 'Color Category' and 'Secondary Sort' as 'Type', all multicolor cards are lumped into one category. This is somewhat counter-intuitive...when I think of 'color category', I generally think of guild/shard names. 'Multi-colored' seems most useful as a higher-level category, opposed to 'mono-colored'. Each of those higher level categories includes multiple color categories.

My suggestion is to do something similar to what Cubetutor does in its display, where the multicolored column has three levels of distinction, the first being 'primary sort', the second always being guild/shard, and the third being the 'secondary sort'. I think this would be very helpful and make more intuitive sense, even if it introduces a certain level of inconsistency in the columns.

**Comment by dekkerglen** [comment] 2019-09-30 17:38
Duplicate of #508

**Closed by dekkerglen** 2019-09-30 17:38 UTC
