### ISSUE TITLE
Card Viewer Showing Blank Line

### ISSUE THREAD

**Issue by cyandev** [dekkerglen/CubeCobra#552] opened 2019-10-01 02:38 UTC
**Describe the bug**
When moving the mouse fast enough, the card display doesn't load an image and then doesn't disappear, and is a white line attached to the pointer.

**To Reproduce**
1. Go to a cube
2. Move your mouse very fast along the left edge of the white section, loading many card images, and quickly move it away.
3. The white line will be stuck to your pointer. It is very visible when you move your mouse near cards.

**Expected behavior**
The card display should disappear when hovering is done and the image isn't loaded.

**Additional context**
This may be an issue with events, I'm not familiar with the project and how the card display works, just a potential cause.

**Comment by cyandev** [comment] 2019-10-01 02:40
Somehow deleted the section saying this is on windows 10 desktop.

**Comment by phulin** [comment] 2019-10-01 04:34
Thanks - this is a duplicate of #488

**Comment by dekkerglen** [comment] 2019-10-01 13:47
Closed #488, use that issue as a reference when working on this one

**Comment by cyandev** [comment] 2019-10-07 03:43
If nobody is working on this can someone assign me? I haven't worked on anything here but I am interested in helping out. My experience is extremely limited.

**Closed** 2019-11-09 14:56 UTC
Labels: bug, help wanted
